class IdentityDomainError(Exception): ...
class TenantNotFound(IdentityDomainError): ...
class UserNotFound(IdentityDomainError): ...
class EmailAlreadyExists(IdentityDomainError): ...
class InvalidCredentials(IdentityDomainError): ...
class AccountLocked(IdentityDomainError): ...
class ForbiddenRoleEscalation(IdentityDomainError): ...
